### ISSUE TITLE
iOS Safari native color picker opens first

### ISSUE THREAD

**Issue by BazzoKelesh** [Ennoriel/svelte-awesome-color-picker#18]
First of, very nice library.

**Issue**
On iOS 16.1.1 Safari the native browser color picker opens first when I click on the color picker component. I have to close the native picker first to use the library picker. It works as expected on desktop Safari and Chrome.

Would love a fix! Thanks.

**Comment by Ennoriel** [comment]
Thanks for the feedback!

I don't have any iOS device. It'll be difficult for me to fix it without a little more info.

Can you test out [this REPL](https://svelte.dev/repl/76af0fc3435e4423be6a00e68c795e22?version=3.55.0) on the same device/browser and tell me if the native color picker also opens up? 

The input should fallback to a native color input when javascript is broken / deactivated. The [input code](https://github.com/Ennoriel/svelte-awesome-color-picker/blob/master/src/lib/components/variant/default/Input.svelte) is rather simple. The library picker dialog is openned in [another file](https://github.com/Ennoriel/svelte-awesome-color-picker/blob/f3beb9b4040164e707e6fc7d924f26392b8e3136/src/lib/components/ColorPicker.svelte#L91-L99) (to handle closing more easily).

Have a nice day!

**Comment by BazzoKelesh** [comment]
Yes it still opens. But, when I change on:click|preventDefault to on:mousedown|preventDefault, it does not open, meaning it would fix the issue?

**Comment by Ennoriel** [comment]
It would fix the issue but I see it more as a workaround than a fix. It's probably working because mousedown is called before click. If it's the only solution, I'll do it anyway.

Before that, last test, can you try pasting this code in a plain `index.html` file and test on the same device/browser?

```html
<html>
  <head>
    <script type="text/javascript">
      function doPreventDefault(e) {
        e.preventDefault();
      }
      
      setTimeout(() => {
        document.getElementById('input').addEventListener('click', doPreventDefault)
      }, 0)
    </script>
  </head>

  <body>
    <input id="input" type="color"></button>
  </body>
</html>
```

If the native color input opens, it's an issue with safari...

**Comment by BazzoKelesh** [comment]
It opens the native color picker on click.

I notice, the native picker is iOS and not Safari, so the issue persists also on Chrome iOS. Like select inputs, the color picker opens a iOS UI. On desktop, browsers have their own UI, so depending on the browser, you will see different UI's for color and select inputs.

**Comment by Ennoriel** [comment]
Thanks!

I'll replace the on:click by on:mousedown ;)

**Comment by Ennoriel** [comment]
I published a new version. Let me know if that solves the issue

**Comment by BazzoKelesh** [comment]
Yes, it did solve the issue, but only for the input, when I click the label instead, the native color picker appears first again. 

Maybe add the mousedown event to the label also/instead?

Something else: My end goal was a div block act as the trigger, but couldn't find it in the documentation. Like just trigger a div block to open the custom color picker, instead of the default color box + label u see now.

Thanks for the fix!

**Comment by Ennoriel** [comment]
Does [this example](https://svelte.dev/repl/76af0fc3435e4423be6a00e68c795e22?version=3.55.0) solve the label click as well?

I haven't tried it yet but `isOpen` is exported and you can try to change it to `true`. It might not work based on the internal event workflow but we'll find a solution.

I don't know your full example but you can also override part of the component, more especially the input.

**Comment by BazzoKelesh** [comment]
Yes, the example solves the label click.

isOpen works, but I how do I hide or replace the default input + label?

**Comment by BazzoKelesh** [comment]
Maybe something like this:
`<label
	on:click|preventDefault={() => {
		/**/
	}}
	on:mousedown|preventDefault={() => {}}
>
	<input
		type="color"
		on:click|preventDefault={() => {
			/**/
		}}
		on:mousedown|preventDefault={() => {
			/**/
		}}
		class:hidden={$$slots.customTrigger}
	/>
	<div>
		<slot name="customTrigger" />
		{#if !$$slots.customTrigger}
			input color label
		{/if}
	</div>
</label>

<style>
	input[type='color'].hidden {
		display: none;
	}
</style>`

Or make the slot outside the label wrapper, to prevent styling issues.

**Comment by Ennoriel** [comment]
Hello @BazzoKelesh ,

I'll also add the preventDefault on the label.

You can override the components with the ones available in the library. But you can also rewrite all the components. So you can rewrite the Input component entierly if you'd like. The doc is here: https://svelte-awesome-color-picker.vercel.app/#components.

Let me know if you can find a way to suits your needs without changing the library.
