### ISSUE TITLE
colorPicker z-index 

### ISSUE THREAD

**Issue by ayamkv** [Ennoriel/svelte-awesome-color-picker#28]
I'm having trouble with changing the z-index of the color picker,
maybe change the default z-index value to 50?

![screenshot](https://user-images.githubusercontent.com/65036385/218287162-4f9c3946-7152-450d-8036-0f923d2570df.jpg)

**Comment by Ennoriel** [comment]
Hello

Do you have a repl where I can reproduce the situation ?

Have you tried to override the `z-index`?

**Comment by ayamkv** [comment]
Hi,
i have tried overriding the `z-index` with a wrapper, and i don't think it does anything.

• repl
https://stackblitz.com/github/ayamkv/luasa/tree/ui?file=package.json

• git repo
https://github.com/ayamkv/luasa/tree/ui

**Comment by Ennoriel** [comment]
Hello!

Please, try to simplify your examples (in general not just for this issue) as much as possible as it helps the maintainers to understand your problem faster.

I will make the z-index of the wrapper configurable. In the meantime, you can override the z-index with the `:global` directive:

```
:global(.color-picker .wrapper) {
    z-index: 200 !important;
}
```

here is the associated [REPL](https://svelte.dev/repl/80078f6d383a4ddfa133fe38b014c9cc?version=3.55.1) to make it work.

**Comment by Ennoriel** [comment]
I fixed that issue and released a new version with a new css variable `--picker-z-index`
