### ISSUE TITLE
Console warning message on page load

### ISSUE THREAD

**Issue by Frank-D** [Ennoriel/svelte-awesome-color-picker#29]
Thanks for this cool svelte component.

Would it be possible to get rid of the annoying warning message in the browser's console upon loading this component on page?

Console warning message:
`The specified value "" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.`

This is happening even when providing a valid hex value to the bind:hex component parameter, so the warning msg doesn't make too much sense actually to the outside world (consumers of this component), and perhaps it is just an internal timing issue that should probably be fixed.

Here's a screenshot taken from your documentation page having the same warning messages (4 times on page-load):
![svelte-awesome-color-picker-warning-msg](https://user-images.githubusercontent.com/6005986/229379221-cea8d82f-755d-466e-8e4f-08cecc9e6053.png)

Thanks

**Comment by Ennoriel** [comment]
Hey @Frank-D 😀 

Thanks for reporting this! It seems that a simple `<input type="color" value="#123456" />` is leading to the same console warning. I filled an issue in the Svelte repository!

See how it goes :)

**Comment by Frank-D** [comment]
Oh wow, I see I see... ; -)
Indeed, I could easily reproduce with the simple color input above;) 

Thanks for looking into this @Ennoriel and filing the ticket against svelte, merci bcp!
