### ISSUE TITLE
Color picker cut off in `overflow: auto` parent

### ISSUE THREAD

**Issue by wtachau** [Ennoriel/svelte-awesome-color-picker#30]
First of all, thanks for this great library! So glad it exists.

I'm currently using this color picker in a menu that has many options, and needs to scroll. However, having `overflow: auto` on the parent of the menu elements (which is necessary for the menu to scroll) then makes the color picker cut off.

Example here: https://svelte.dev/repl/1adad297477644fdb865d0a2774aa73a?version=3.55.1

Is there some magic CSS I'm not aware of that would fix this?

Things that I think might fix this:
* Magic CSS that I don't know of
* Having the color picker be a global absolutely positioned element on top of the rest of the page (a la https://tippyjs.devjs.cn/)
* Being able to render just the color picker without the input, so that we can control its placement + location in the DOM.

Let me know if you need any more detail or if I'm missing anything. Thanks!

**Comment by Ennoriel** [comment]
Thanks for your kind issue 😃

This is a problem I am aware of. There is a different issue opened to make z-index configurable (https://github.com/Ennoriel/svelte-awesome-color-picker/issues/28) and a discussion on a PR to place the picker at the center of the screen on mobile (https://github.com/Ennoriel/svelte-awesome-color-picker/pull/20#issuecomment-1387032357) which are both more or less related.

At the moment, there are 2 solutions to display the color picker without the input:

* you can define your own <Input/> component (https://github.com/Ennoriel/svelte-awesome-color-picker#input)
* do not display the Input with `isInput={false}`

I know a solution to solve your issue described here: https://css-tricks.com/popping-hidden-overflow/. I don't know how that would be implemented in (or on top of) the library but if it's in the library it should still work in standard conditions.

Would you be willing to try fixing it and maybe make a PR?

**Comment by wtachau** [comment]
Hi @Ennoriel , I poked around this for a little while but couldn't get something working— perhaps it will be easier for you as you're more familiar with the library? The solution in the css-tricks site you linked uses javascript to position the element when it's placed everywhere, and I'm not sure how to ensure that will work in all standard conditions. 

I'm a little surprised this issue hasn't come up before— having a color picker in a menu that could overflow seems like a fairly common use case.

**Comment by Ennoriel** [comment]
The popup is now positionned according to the `<div id="test>` element. I can see that it's good for the overflow property but not for positionning. You can still listen to the input position and update the wrapper element accordingly. It's far from optimal but that's what I would do if I had to implement it inside the color-picker (that I am considering to do in the future)
