### ISSUE TITLE
Please propagate `mousedown` and other events

### ISSUE THREAD

**Issue by FluffyDiscord** [Ennoriel/svelte-awesome-color-picker#32]
I would like to listen to `mousedown` event on the parent element wrapping around the color picker, but I can not since its `preventDefault` and `stopPropagation`

https://github.com/Ennoriel/svelte-awesome-color-picker/blob/master/src/lib/components/Picker.svelte#L148

Would it be possible to disable it, or make it configurable - preventing by default?

**Comment by Ennoriel** [comment]
May I ask you what is your use case? There may be workarounds ;)

I'll consider removing them or make them configurable

**Comment by FluffyDiscord** [comment]
I have the color picker in tooltip that automatically closes when cursor leaves the tooltip element. The issue is that when user drags the color picker around and mouse leaves the tooltip, it closes. I would like to detect mousedown on the color picker parent element, disable auto tooltip hiding, and then on mouseup enable it again.

**Comment by Ennoriel** [comment]
Thanks

**Comment by Ennoriel** [comment]
I removed the stopPropagation that were not useful anymore ;)
