### ISSUE TITLE
isAlpha and canChangeMode props don't work

### ISSUE THREAD

**Issue by nickpoulos** [Ennoriel/svelte-awesome-color-picker#33]
Using version 2.4.3, it appears the most basic usage of these two props do not work correctly.

```
<ColorPicker label="" canChangeMode="false" isAlpha="false" bind:rgb />
```

The label prop is picked up and shows no label, however neither of the other two props are being recognized. Both the Alpha slider and the RGB mode button are still visible.

**Comment by Ennoriel** [comment]
Thanks for using the library @nickpoulos !

The two props are boolean, not strings. Here is how they would work 😄 :

```
<ColorPicker label="" canChangeMode={false} isAlpha={false} bind:rgb />
```

**Comment by nickpoulos** [comment]
Thanks for making it! and thank you for the quick response, much appreciated. 

Oh wow stupid mistake on my part for sure. 

It still might be worth throwing an example or two in the Read Me just so you don't have to keep dealing with these kind of dumb issues from the n00bs like myself.  :)
