### ISSUE TITLE
Question: How to have multiple pickers in the same component?

### ISSUE THREAD

**Issue by sanderjson** [Ennoriel/svelte-awesome-color-picker#34]
We are binding the color variable, how to have multiple independent pickers? Instead of `bind:rgb => rgb.r, rgb.b, rgb.g` I would like to `bind:picker_01 => picker_01.rgb.r, picker_01.rgb.b, picker_01.rgb.g` Is this already available? Sorry if I missed it in the docs.

**Comment by Ennoriel** [comment]
Hi @sanderjson 

You can do that by binding to another variable:

```
<ColorPicker bind:rgb={rgb_1} />
<ColorPicker bind:rgb={rgb_2} />
```
