### ISSUE TITLE
The color picker is always hiding when mouse is clicked outside of the component

### ISSUE THREAD

**Issue by JanRoma** [Ennoriel/svelte-awesome-color-picker#37]
**Current behavior**: When mouse is clicked outside of the opened color picker it's isOpen value is changed and it's being closed.

**Expected behavior**: There is a flag for changing the default behavior, so the color picker is closed:
-  When button is clicked OR when the mouse down button is clicked outside of the component
- ONLY when the button is clicked

It will make the picker more customizable.

**Comment by JanRoma** [comment]
I have the code proposition ready, but can't push to the repo (Access denied)
If you could help me out with that, I am glad to make a PR.

**Comment by Ennoriel** [comment]
Thanks! I published a new release. I renamed the props `disableCloseClickOutside`!
