### ISSUE TITLE
CircleVariant doesn't exist?

### ISSUE THREAD

**Issue by johnrichardrinehart** [Ennoriel/svelte-awesome-color-picker#39]
# Description
I was trying to walk through the set-up instructions of this project but failed to use the `CircleVariant`. Below is a patch that I applied to a local checkout of this repo at 38ad0e9afaabe21d91cd38ef62cba7a1c0da3ee2 (after trying in my own project) which can reproduce this problem:
```diff
diff --git a/src/routes/+page.md b/src/routes/+page.md
index 2253923..513d71e 100644
--- a/src/routes/+page.md
+++ b/src/routes/+page.md
@@ -1,6 +1,6 @@
 <script lang="ts">
     import './style.css';
-       import ColorPicker, { ChromeVariant, A11yHorizontalWrapper } from '$lib';
+       import ColorPicker, { CircleVariant, ChromeVariant, A11yHorizontalWrapper } from '$lib';
     import { browser } from '$app/environment';
 
     let hex = "#f6f0dc";
 ```
 
 Is this expected? I couldn't find `CircleVariant` in `src` so maybe it just doesn't exist? But, then I'm wondering why the documentation mentions it.

**Comment by Ennoriel** [comment]
Thanks for your issue. The circle variant is the default displa since version 2. I didn't update the documentation accordingly at that time. Sorry about that.

I did it now 😃

**Comment by johnrichardrinehart** [comment]
Oh, okay. I was thinking I was missing something :laughing: !

Thanks for patching the docs!
