### ISSUE TITLE
Type error in `components` prop

### ISSUE THREAD

**Issue by probablykasper** [Ennoriel/svelte-awesome-color-picker#4]
When passing custom components, I'm getting this type error:
```
Type 'typeof ColorPickerWrapper__SvelteComponent_' is missing the following properties from type 'SvelteComponentTyped<{ wrapper: HTMLElement; isOpen: boolean; isPopup: boolean; toRight: boolean; }, { [evt: string]: CustomEvent<any>; }, { default: {}; }>': $set, $on, $destroy, $$prop_def, and 5 more.ts(2740)
```

I'm using it like this:

**Index.svelte**
```svelte
<script lang="ts">
	import ColorPickerWrapper from './ColorPickerWrapper.svelte';
	import ColorPicker from 'svelte-awesome-color-picker/ColorPicker.svelte';
</script>

<ColorPicker components={{ wrapper: ColorPickerWrapper }} />

```

**ColorPickerWrapper.svelte**
```svelte
<script lang="ts">
  export let wrapper: HTMLElement
  export let isOpen: boolean
  export let isPopup: boolean
  export let toRight: boolean
</script>

<div
  class="rounded border border-gray-300"
  bind:this={wrapper}
  class:isOpen
  class:isPopup
  class:to-right={toRight}
>
  <slot />
</div>
```

**Comment by Ennoriel** [comment]
Hi @probablykasper!

Thanks for using the lib and for filling this issue.

I tried to reproduce by initializing a new svelte-kit project with `npm init svelte` and adding `ColorPickerWrapper.svelte` and it seems to work perfectly fine in dev and build mode.

What environment are you using? svelte kit ? rollup ? How did you import `ColorPicker`?

**Comment by probablykasper** [comment]
Went and reproduced it like this:
1. `npm init svelte` (Skeleton project, enable TypeScript, ESLint, Pretter)
2. `npm i`
3. `npm i -D svelte-awesome-color-picker`
4. Paste `index.svelte` and `ColorPickerWrapper.svelte` from above
5. `npm run check`

**Comment by Ennoriel** [comment]
Thanks! I never used `npm run check` before but I will from now on!

I released the version 0.0.9 with the component types fixed. 🔥 

You might still see typescript errors about `Color`. I'll fix them later.

**Comment by probablykasper** [comment]
Hmm, getting this error on the latest version 🤔 It seems like there aren't any `.svelte` file in the package root
```
Cannot find module 'svelte-awesome-color-picker/ColorPicker.svelte' imported from '/Users/k/dev/git/limey/src/lib/color-picker/ColorPicker.svelte'
Error: Cannot find module 'svelte-awesome-color-picker/ColorPicker.svelte' imported from '/Users/k/dev/git/limey/src/lib/color-picker/ColorPicker.svelte'
    at viteResolve (/Users/k/dev/git/limey/node_modules/vite/dist/node/chunks/dep-611778e0.js:58387:25)
    at nodeImport (/Users/k/dev/git/limey/node_modules/vite/dist/node/chunks/dep-611778e0.js:58422:15)
    at ssrImport (/Users/k/dev/git/limey/node_modules/vite/dist/node/chunks/dep-611778e0.js:58319:20)
    at eval (/src/lib/color-picker/ColorPicker.svelte:11:37)
    at async instantiateModule (/Users/k/dev/git/limey/node_modules/vite/dist/node/chunks/dep-611778e0.js:58364:9
```

On a side note, the way I export components in SvelteKit is without having any `entry` or `svelte` property in `package.json`, and then having re-exporting components/types from `src/lib/index.ts` like this:
```
```

**Comment by Ennoriel** [comment]
I am really sorry about that.
I released the 0.0.10 version.
It should have everything now. :)

**Comment by probablykasper** [comment]
That's no problem at all! I appreciate your work on this :)

**Comment by Ennoriel** [comment]
Hello @probablykasper 

I release a version 1.0.0 version with the types fixed. The API has slightly changed: instead of a color object, there are now three variables: rgb, hsv and hex.

Please let me know if it's working for you!
