### ISSUE TITLE
Slider Issue

### ISSUE THREAD

**Issue by johnrichardrinehart** [Ennoriel/svelte-awesome-color-picker#40]
# Description

The hue and transparency sliders don't align with the mouse click (the dot on the axis lags the mouse) and the horizontal axis is strangely truncated at the right. The slider hits a wall on the right side. I've tried to demonstrate this with a screen capture. Please let me know if something's unclear.

https://github.com/Ennoriel/svelte-awesome-color-picker/assets/6321578/9bd40c5d-5f96-47c5-af2d-272740597ab1

**Comment by Ennoriel** [comment]
Hi @johnrichardrinehart 

Thanks for the issue! What browser / OS are you using? Do you see any warning/error on your console?

**Comment by Ennoriel** [comment]
It's fixed :)

**Comment by johnrichardrinehart** [comment]
Sorry, mate. I just jumped on vacation and wasn't looking at GitHub. It looks pretty good, now! Thanks for fixing it!
