### ISSUE TITLE
Vertical Slider Issue

### ISSUE THREAD

**Issue by johnrichardrinehart** [Ennoriel/svelte-awesome-color-picker#41]
# Description
This seems related to #40. When this component is used like
```typescript
  <ColorPicker
    toRight={true}
  />
  ```
(without a `components` property) the sliders are difficult to use - the slider position seems to not match the cursor position very well. Please see the video for a comparison of the behavior fixed in #40 with this ostensibly broken behavior.

Thanks for your hard work with this package! Full disclosure: I'm not using this dependency, anymore, since I changed my application. So, there's no rush to fix! I _may_ reinstate this dependency and other people probably depend on this behavior - so, I think it would be good to have it fixed.
 
 https://github.com/Ennoriel/svelte-awesome-color-picker/assets/6321578/76bda8f8-1fce-4c0e-ac4d-dc80f81a215c

**Comment by Ennoriel** [comment]
This is the correct behavior. I made it clearer in the documentation as well, thanks!

**Comment by johnrichardrinehart** [comment]
> 

Thanks for addressing this. However, it kind of reads like "if you are (at the time you are) overriding components then you need to use this property". I kindly suggest a rephrase to something like "this requires also setting/overwriting the components property lest you encounter #41".
