### ISSUE TITLE
Console warning: ''[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive."

### ISSUE THREAD

**Issue by caseyplummer4haliontech** [Ennoriel/svelte-awesome-color-picker#44]
Using Svelte 4.0.3

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/69089120/4d044387-37c8-46ce-b18d-5f140e24a42d)

See:
https://chromestatus.com/feature/5745543795965952

**Comment by Ennoriel** [comment]
Hey,

Thanks for using the library!

Can you be a little bit more specific?

Thanks!

**Comment by Ennoriel** [comment]
@caseyplummer4haliontech can you please elaborate on this issue? Which browser are you using? Where and when are you seeing this issue? I cannot reproduce on the doc site!

**Comment by Ennoriel** [comment]
I am closing this as I cannot reproduce. Reopen it when you have time to give me some insights ;)

**Comment by panos-stavrianos** [comment]
This is happening to me also in a clean project on Chrome Version 117.0.5938.92 (Official Build) (64-bit) (Linux), but not in Firefox.

**Comment by Ennoriel** [comment]
This issue is fixed in the version 3 (still in beta)
