### ISSUE TITLE
Is there a way to get full width on all elements?

### ISSUE THREAD

**Issue by isaacfink** [Ennoriel/svelte-awesome-color-picker#46]
Is there a way to specify a full width for the picker and slider elements, even if I set it with css the clicks don't register at the correct coordinates

**Comment by Ennoriel** [comment]
Thanks for using the library!

Do you have a REPL to show what you exactly did? I haven't considered a full width case until now so it's most probably not handled correctly.

**Comment by isaacfink** [comment]
@Ennoriel here is a repl https://svelte.dev/repl/e296a6b48bfa430689293f59c8ce37cc?version=4.1.1 as you can see I am trying to get everything to be full width, but the cursor positions are not calculated correctly, is there a different way of doing this or is it something that is not implemented?

**Comment by isaacfink** [comment]
The issue is only on the main color picker not on the other sliders

**Comment by Ennoriel** [comment]
Thanks for the REPL. It's clearer!

Try to apply the css variable `--picker-width` to you wrapper and let me know if that solves your issue:

```
.wrapper{
  max-width:500px;
  background:gray;
  --picker-width: 100%;
}
```
