### ISSUE TITLE
Cannot enter Hex value with text field

### ISSUE THREAD

**Issue by clairecassan** [Ennoriel/svelte-awesome-color-picker#53]
Hi, 
I started using your library only today, so maybe I missed something. I cannot type an hex value, when I type the last character the value reverts to the current color, and I don't get the input event. I have attached a video.

https://github.com/Ennoriel/svelte-awesome-color-picker/assets/65108365/6b81763f-e4aa-4599-8cef-b5ca36f4f6a3

Thank you
cl.

**Comment by Ennoriel** [comment]
Hi @clairecassan 

Thanks for using the library!
Can you share a [REPL](https://svelte.dev/repl) close to your codebase that would reproduce the issue? I cannot reproduce it on the [documentation site](https://svelte-awesome-color-picker.vercel.app/).

Thanks :)

**Comment by clairecassan** [comment]
Hi!
I trimmed it down: 
[ColorPicker_Test.zip](https://github.com/Ennoriel/svelte-awesome-color-picker/files/12515986/ColorPicker_Test.zip)
I am still on svelte 3.
Thanks
Claire

**Comment by Ennoriel** [comment]
Can you save the REPL online (you have to sign in with your github account) and share a link? I prefer not to download any zip file ;)

**Comment by clairecassan** [comment]
<script>
	import { writable, get } from 'svelte/store';
	import ColorPicker from 'svelte-awesome-color-picker';
	import _  from 'lodash';
	
	const defaultGraphStyle = {
          // pattern colors
         stitchOnColor:"#000000"
        }
	const graphStyle = writable(_.cloneDeep(defaultGraphStyle));

	const changeStitchColor = (value) => {
            const color = value.detail.hex;
            let gStyle = _.cloneDeep(get(graphStyle));
            gStyle.stitchOnColor = color;
            console.log(`in event with color ${color}`);
            graphStyle.set(gStyle);
       }

	$: {
            console.log(`in effect with color ${stitchOnColor}`);
        }

	// failing version
	let stitchOnColor; 
       $: {
            console.log(`in effect with graph ${$graphStyle.stitchOnColor}`);
            stitchOnColor = $graphStyle.stitchOnColor;
        }
	// working version
	/*
	let stitchOnColor = get(graphStyle).stitchOnColor;
       $: {
           console.log(`in effect with graph ${$graphStyle.stitchOnColor}`);
	}
	*/
</script>

Pattern color
<ColorPicker bind:hex={stitchOnColor} on:input={changeStitchColor} label="Regular"/>

**Comment by Ennoriel** [comment]
This is a tricky situation.

- The picker (the square are to chose the color from) updates the hsv value internally and triggers the color conversion (to rgb & hex internally first
- The hex input however does trigger your reactive assignment before the internal color conversion one (which should be ok in a normal case). However in your reactive assignement, you rollback the value: `stitchOnColor = $graphStyle.stitchOnColor;`

Can you just bind to your store?

```svelte
<script>
	import ColorPicker from 'svelte-awesome-color-picker';
	import { writable } from 'svelte/store';
	
	const colors = writable({
		stitch: "#123456"
	});
</script>

<pre>{JSON.stringify({$colors}, null, 2)}</pre>

<ColorPicker bind:hex={$colors.stitch} />
```

**Comment by clairecassan** [comment]
Yes, I can bind differently. Thanks.
