### ISSUE TITLE
How to use the css variables?

### ISSUE THREAD

**Issue by henrygrant** [Ennoriel/svelte-awesome-color-picker#54]
I'm a little confused on how to set the css variables. I've tried setting the variables globally, but that didn't take. Can you provide an example of setting one of these?

**Comment by henrygrant** [comment]
Oh! I was using them right the whole time, I just didn't realize those were styling the picker itself rather than the circle that summons the picker.

Unfortunately, this doesn't solve anything for me as I was hoping to resize the circle. 

Do you have a way to do that?

**Comment by Ennoriel** [comment]
I'll try to make this a css variable in a later release!

In the meantime, you can override the css values:

```svelte
<div class="wrapper">
	<ColorPicker bind:hex={$colors.stitch} />
</div>
	
<style>
	.wrapper :global(label .alpha), .wrapper :global(label .color) {
		width: 50px !important;
		height: 50px !important;
		border-radius: 25px !important;
	}

	.wrapper :global(label input) {
		margin: 0 20px !important;
	}
</style>
```

The wrapper is not necessary but prevent the css to affect all your othe components.
