### ISSUE TITLE
Integer Color Support

### ISSUE THREAD

**Issue by Arbee4ever** [Ennoriel/svelte-awesome-color-picker#57]
Hey, could you add support for integer colors?
https://sabe.io/blog/javascript-hex-to-decimal

**Comment by Ennoriel** [comment]
Thanks for the feature request!

I am not sure what you are asking for here. Can you provide an example? How would you write #13579B for example?

**Comment by Arbee4ever** [comment]
That would be: 1267611

**Comment by Arbee4ever** [comment]
To calculate it, you'd have to to r * g * b to get the value

**Comment by Arbee4ever** [comment]
But js natively has `parseInt(hex, 16);`

**Comment by Ennoriel** [comment]
What is the use case of having the value in decimal?

By the way, `#13579B` is equivalent to `rgb(19, 87, 155)`. And `(r + 1) * (g + 1) * (b + 1) = 20 * 87 * 155 = 269700`

**Comment by Arbee4ever** [comment]
The Discord API only accepts integer colors. This would reduce the conversion work I'd have to do

**Comment by Ennoriel** [comment]
I'll think about adding it in the future but it also adds extra computation for everyone even when the decimal color format is not needed.

Would you be ok to use a custom component in the meantime like the one in this repl: [https://svelte.dev/repl/27c4d82b45744dadabf2fdf24706c97a?version=3.44.3](https://svelte.dev/repl/27c4d82b45744dadabf2fdf24706c97a?version=3.44.3)?
