### ISSUE TITLE
How To Avoid Overflow Body?

### ISSUE THREAD

**Issue by skyslide22** [Ennoriel/svelte-awesome-color-picker#58]
Imagine you have a vertical tool floating on the right, when the color picker popup opens, the body/container will overflow.

Repl: <https://svelte.dev/repl/9a44afe822dd4fb6bb35529e6e28c326?version=3.59.1>

Is it planned to implement a feature that allows the popup to be `position: fixed` and spawn on below the color picker button considering staying inside he `<body>` or specified container?

**Comment by Ennoriel** [comment]
Have you tried the solution proposed in the "how to" section of the documentation? https://svelte-awesome-color-picker.vercel.app/#fix-overflow-issues

**Comment by Ennoriel** [comment]
I'm closing this issue. Don't hesitate to comment if you have some troubles with the solution provided.
