### ISSUE TITLE
[Question] Is it possible to add a dark theme to the picker?

### ISSUE THREAD

**Issue by MordechaiHadad** [Ennoriel/svelte-awesome-color-picker#59]
I am wondering if it's possible to add dark colors for the UI of the picker, or just change the colors of the UI to go according to a website's theme.

**Comment by MordechaiHadad** [comment]
What do you mean exactly by doing the dark theme?

**Comment by Ennoriel** [comment]
I added a solution to style the dark theme in the v3. You can test it out in the beta version. It's going to be released soon! The documentation site is available: https://svelte-awesome-color-picker-git-v300-ennoriel.vercel.app/.

**Comment by MordechaiHadad** [comment]
> I added a solution to style the dark theme in the v3. You can test it out in the beta version. It's going to be released soon! The documentation site is available: [svelte-awesome-color-picker-git-v300-ennoriel.vercel.app](https://svelte-awesome-color-picker-git-v300-ennoriel.vercel.app/).

I will try it thank you! I have another request/question.
Is is possible to make a custom button that opens the color picker or do i still have to use the input thingy.

**Comment by Ennoriel** [comment]
I released the version 3 today so you don't need to use the beta version anymore.

You can override most of the components, including the input. It's all documented and you can copy/paste/modify the default one that you can find [here on Github](https://github.com/Ennoriel/svelte-awesome-color-picker/blob/master/src/lib/components/variant/default/Input.svelte).

**Comment by MordechaiHadad** [comment]
So I can just use the color picker by itself without having to use all of this?
![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/33547558/c0b5282f-9836-4c12-af90-f2f0141258d0)

**Comment by MordechaiHadad** [comment]
Okay i just checked you can, could you also add in class attribute `$$props.class` so I can pass my own css classes?
