### ISSUE TITLE
Unintended Mouse Events

### ISSUE THREAD

**Issue by jrmoynihan** [Ennoriel/svelte-awesome-color-picker#6]
First, thanks for the nice component!  The alpha channel slider is a nice upgrade over the default browser `<input type="color">` element.  

I noticed two issues while using the component though:

1.  Mouse events are still detected on elements _behind_ the picker.
2. Drag-select regions still appear while holding down the mouse and moving around the picker.

I think these can both be solved by placing `preventDefault` and `stopPropagation` modifiers on the `mousedown` and `touchmove` events (another moment that makes me love Svelte!):

```svelte
	<div
		class="picker"
		tabindex="0"
		bind:this={picker}
		on:mousedown|preventDefault|stopPropagation={pickerMouseDown}
		on:touchstart={touch}
		on:touchmove|preventDefault|stopPropagation={touch}
		on:touchend={touch}
		style="--color-bg: {colorBg?.hex};">
		<svelte:component
			this={components.pickerIndicator}
			{pos}
			color={hsv2Color({ h, s, v, a: 1 })} />
	</div>

**Comment by Ennoriel** [comment]
Hello @jrmoynihan !

I will add that in the next release! Thanks for the issue :)

**Comment by Ennoriel** [comment]
Hello @jrmoynihan !

It should be good! Let me know if you still see some improvements that could be made!

Thanks for using the lib! :)
