### ISSUE TITLE
Can you change the .container css class in Input.svelte to another?

### ISSUE THREAD

**Issue by ren3104** [Ennoriel/svelte-awesome-color-picker#60]
Can you change the `.container` css class in `Input.svelte` to another? Because many css frameworks have this class too, such as Bulma, Specter, Milligram, SemanticUI and etc.

**Comment by Ennoriel** [comment]
I'll do that in the version 3! (if the container still exists) and I'll check the other class names. I recommand you to switch to the version 3 in beta, especially if you override some classes.
