### ISSUE TITLE
Be able to pass class using `$$props.class`

### ISSUE THREAD

**Issue by MordechaiHadad** [Ennoriel/svelte-awesome-color-picker#61]
It would be cool to be able to pass your own css classes to the color picker, and it will require one line to be changed.
Example:
https://svelte.dev/repl/6de3c939fcbf4c90a0309210c04e1c3a?version=3.17.2

My main reasoning behind this:
1. I can use tailwindcss dark theme solution
2. I would like to set the color picker location as absolute
3. responsive design ig?

**Comment by Ennoriel** [comment]
I understand what you want to do here but I'm not sure that the proposed solution is the right one. In the library there are a lot more that one HTML element. Exporting a class props would only make one HTML element class overridable.

You can already use tailwindcss to style the component by:

1. [overriding the components](https://svelte-awesome-color-picker.vercel.app/#components)
2. [overriding the css variables](https://svelte-awesome-color-picker.vercel.app/#components):

```svelte
:global(.dark) .my-color-picker-wrapper {
        --cp-bg-color: theme(colors.gray.800);
        --cp-border-color: theme(colors.white);
        --cp-input-color: theme(colors.gray.500);
        --cp-button-hover-color: theme(colors.gray.700);
    }
```

3. overriding the styles applied to the color-picker classes with the [`:global` directive](https://svelte.dev/docs/svelte-components#style)

Is ont of the proposed solution enough or is there something that you cannot do with that?

**Comment by MordechaiHadad** [comment]
> I understand what you want to do here but I'm not sure that the proposed solution is the right one. In the library there are a lot more that one HTML element. Exporting a class props would only make one HTML element class overridable.
> 
> You can already use tailwindcss to style the component by:
> 
>     1. [overriding the components](https://svelte-awesome-color-picker.vercel.app/#components)
> 
>     2. [overriding the css variables](https://svelte-awesome-color-picker.vercel.app/#components):
> 
> 
> ```svelte
> :global(.dark) .my-color-picker-wrapper {
>         --cp-bg-color: theme(colors.gray.800);
>         --cp-border-color: theme(colors.white);
>         --cp-input-color: theme(colors.gray.500);
>         --cp-button-hover-color: theme(colors.gray.700);
>     }
> ```
> 
>     3. overriding the styles applied to the color-picker classes with the [`:global` directive](https://svelte.dev/docs/svelte-components#style)
> 
> 
> Is ont of the proposed solution enough or is there something that you cannot do with that?

What about having an exported variable that is a js object with fields that correspond to their specific element? this is how i do it on a non svelte library i made

**Comment by MordechaiHadad** [comment]
hmmm I checked `:global()` actually works for your lib i wonder why mine doesn't, Fair enough no use case for what I wanted then.
Then I suggest adding in the docs the css classes that you could overwrite with `:global` like "input container" etc.
