### ISSUE TITLE
Nullable error when initial value is undefined

### ISSUE THREAD

**Issue by zetokore** [Ennoriel/svelte-awesome-color-picker#64]
Thank you for the nullable addition!

If you init the picker with an undefined value the picker will get stuck at "#ff0000".  If you check"without color" and then uncheck it again that seems to resolve the issue.

**Comment by Ennoriel** [comment]
What do you suggest? I still have to display something. And not displaying anything is not a really good solution either.

What about opacity? https://svelte.dev/repl/e3caa23883594c7bb78438a3bdca163b?version=4.2.9

**Comment by zetokore** [comment]
The problem is there's a JavaScript error causing the color to get stuck at #ff0000, it won't change until you click "without color".

**Comment by Ennoriel** [comment]
Can you show me a REPL and tell me your browser/OS? My example is working even with hex initialized with `undefined`

**Comment by Ennoriel** [comment]
I released a new version. Let me know if the problem is fixed

**Comment by zetokore** [comment]
Fixed, thank you! 🙏
