### ISSUE TITLE
HSV doesn't work in Svelte 5

### ISSUE THREAD

**Issue by jerrygreen** [Ennoriel/svelte-awesome-color-picker#68]
Always `0, 100, 100, 1` no matter what:

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/13215662/eb66914a-73e6-4092-830b-bbdde343f12b)

Even in simplest case where no parameters passed at all:

```svelte
<script lang="ts">
  import ColorPicker from 'svelte-awesome-color-picker'
</script>

<ColorPicker />
```

rgb, hex – they work tho

**Comment by Ennoriel** [comment]
Can you please provide a Repl and the os/browser you are using?

It is working fine here: https://svelte.dev/repl/aab96e19ae3e4b96a592322497b232a7?version=3.59.1

**Comment by jerrygreen** [comment]
By some reason, it works for me in Repl, but doesn't work when I run a pretty simple Svelte application dev server. Here's gif:

![gif4](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/13215662/b8aadf44-0dc6-41fb-8f8f-2bbbf1b33eb3)

OS: Windows 10, version 22H2, build 19045.4046
Browser: MS Edge Version 122.0.2365.52 (Official build) (64-bit)

---

BTW:

- HSV works perfectly fine in `3.0.0-beta.8` somehow, and it worked fine until `3.0.0-beta.11`
- `3.0.0-beta.12 is non-existent so idk, but in `3.0.0-beta.13` it's broken since then

I'm using `svelte@5.0.0-next.67`, so maybe that's related.

**Comment by jerrygreen** [comment]
Just checked with `svelte@4.2.12` – it's compatible with the latest library `3.0.5`

So, it's incompatibility with Svelte 5, indeed.

**Comment by Ennoriel** [comment]
I'm closing this issue in favor of the issue #69
