### ISSUE TITLE
Overwrite components

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [Ennoriel/svelte-awesome-color-picker#7]
Thanks for the library.

Having difficulties overwriting components in a variant.

We basically would like to hide some elements and show only specific components, if possible reordering the layout.

Within the relevant part of the docs, this sytax puzzles me:

`
<ColorPicker bind:rgb components={{...CircleVariant: input: CustomInput}} />
`

What are the colons doing inside the spread brackets?

I get an unexpected token in js and ts on the first colon.

**Comment by Ennoriel** [comment]
Hi @JackLeEmmerdeur ,
It's a typo! It should be:

```
<ColorPicker bind:rgb components={{...CircleVariant, input: CustomInput}} />
```

If you are using the basic variant, you don't need the `CircleVariant` here. If you want to override the Circle or Chrome like ones, you'll need it! ;)

I'm fixing it, thanks :)

**Comment by JackLeEmmerdeur** [comment]
Ah yes, thank you for fixing that.
Now the purpose of the parameter is understandable.
This colorpicker was btw chosen by my co-worker for being the only currently usable and at the same time also fairly customizable in the svelte world.
Hope you'll keep the interest in advancing it further.
Thanks so far.

**Comment by Ennoriel** [comment]
Do you have any suggestion in adding new parameters?
Also, I'd be interested to see your use of the lib if it's visible to everyone. I may add an Example section in the readme with a link to the example/repo.

**Comment by JackLeEmmerdeur** [comment]
No problem. I'll ask my colleague about things that could be improved or added.
Sorry to say I can't give you a link as it's a private tool. 
Our usecase isn't special anyway and seen a myriad times.
If I have an openly accessible page, I'll make sure to give you a link.
