### ISSUE TITLE
z-index of the picker

### ISSUE THREAD

**Issue by adabingw** [Ennoriel/svelte-awesome-color-picker#73]
my current implementation includes using the colour picker in a popup. so the popup has limited height and width. it seems like the colour picker right now is limited by the height and width of the parent div (not entirely sure tho), so i'm wondering if there's a way to position it so that it sticks out of the popup. i tried --picker-z-index with values of -1 and 9999 but those don't work.

here's an image:

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/86745853/16451403-3eb7-457f-91e2-4470c0c1d3a5)

it'd also be helpful if we can change the space between the picker and the label text (as you can see, it's kinda overlapping with my popup, so it'd be great if i can change that)

thanks!

**Comment by Ennoriel** [comment]
Hi @adabingw 

Thanks for using the library :)

Have you checked this Q&A entry: [How to fix overflow issues](https://svelte-awesome-color-picker.vercel.app/#fix-overflow-issues)?
