### ISSUE TITLE
ReferenceError: $$component is not defined  (Svelte5 Runes Mode)

### ISSUE THREAD

**Issue by Dudek-AMS** [Ennoriel/svelte-awesome-color-picker#75]
```svelte
    let value = $state('#ffffff');
....
....
....

    <ColorPicker bind:hex={value}  isDialog={false}/>
```

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/100142218/06879c03-c2e9-46ee-b045-0ee041b163b1)

**Comment by Ennoriel** [comment]
Can you please provide a [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
That would help me a lot!

**Comment by Dudek-AMS** [comment]
https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACpVWbW_bNhD-Kze1qGXUkl103QDFSjekLVBgXYMV2JdpQGnxZHOhSIE8OUkN_feBpOTQcTZsNiBTx3t57rnj0YekERJtUvxxSBRrMSmSn7suWSR037kXu0dJmCwSq3tTO8na1kZ0dFkpABBtpw3BlZbaXIv6Bg00RrdQJfkyEubBTZVUyn9JIkHt9qGE55YYYTp79uHDarVazeYXlVovj1EqtY7db4TixZ7JHsuD9zAsL4PXdQhS7JBxJyKAEStYU5dVsiPqbLFc1lzlxIS8FYrX1ua1bqvkMgq5Xj5ypZJF0mouGoE8Kcj0OCyOfEXo_gNvIJnallVCtkq863-mMPjI2C1a3WLms806r1IlF5Htb2hJG3xkt9V6KzFrGaERTHK0YqsyUWtll6PFsS4XlXIlOfiigqfXVcaRzTYS0_ki7Ei2QTmuA5LPHaoT1YZJi5O-VaLrkK4N7gXeQvlI8A4b1ksalQ1apN_PYlsyfU29QX4ltcLUo5tPEVwRoIRecWyEQh6kAxQnyRRgyQi1jdN4JDtF9raAL0Fwlu3bAjZaS2TqDPfbyecDtkg0uLQ6ozubzi_Gk6BGQEhgmOK6_cihhFkWqh2CZjN4CZ8Y7fKgks5z0l-80_T1D_Pc9psQIv1x8ut8Nr2qSWgV8L3fo6IUC_CL-cSO-2DeGXTSsRwe3cOmJd1dG92xLXPuTnanTnmgYNwcppPunnjn2_QI6EqK-uZzT1ZwTJXmWMCvmqMHFcxdkxLsmOISvTaUkHqMBXzSvcUxi_IyTkQ04N3BixfwnVvktVbEhLLBNidmtkjA7BjP6YUdHlK_DkQgPyHI19K548J2jOpdIPNUwSvhLVz1lnQbNGa1w65DprOFd-KiRzoflaD5qafodYjYdAuu6751eBnn3vwXYQkVmjHUbBGTtgA3qkJPhEal3qg4M46WjL5Pz9I9BjLY6j3-n1jn2D38eL5aupcYbhDI404nvKNGoORQbKXeMJnmLa-9OPPyE6Abbbgz0l0msaHMMC56W8DqoQnXyylWpQ7PxjP-9BQaB8sIe83FHrxtsWH1zdboXvFwKsuD1xyglszaskpGHJsJ0Eay-gY2-i4LAj_pJ9De8WR5m736Hnbu0Ui8g796S6K5z2rXgwYEYWvHF39DcbEfPU3rw3LMZQgZiiaaVC7_OBrbWC17QviWvVlVCYz5ke7Kw9eayTplqt5pkz4_TMNoANLdHF7CKn-D7fzrMNo4vv_FyG3PnXZvsYiPO2gVn4nykPpD_IC59PfHMKV5dvXv8O7Iv7DvBJN6Wx6C0dLf3RMxogl9FzPgWXaPzOhbaCl7PZJsySDVu2OlovKH9DI3zMsoRaMlutr3RFpVCRBz-PCurJLsVZWchjwJAgYlI7HHKpnoeIIH_y8DtLrB-86gteUhxTDwQDQp5jd4D2VZwuy9a4_Z_PQ-9tZD1HaHnwwqjuZR7z80fXwdTSRGXMTpZKwnDU-e20DgqZfp9_xP1J_D33_adHiACgAA

**Comment by Dudek-AMS** [comment]
https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACpVWbW_bNhD-Kze1qGXUkl1s3QDFSjakLVBgXYMV2JdpQGnxZHOmSIE8OckE_feBpGTLcTZsNiBQx7vnnnvhUV1UCYk2yn7vIsVqjLLop6aJFhE9Nu7FHlASRovI6taUTrK2pRENXRcKAETdaENwq6U2d6Lco4HK6BqKKF1OhGmAKaJC-T9JJCjdPuTw0hIjjGcvPnxYrVar2fyqUOvl0Uuh1lP4jVA8OzDZYt55hH55HVDXwUm2Q8adiAAGrmBNmRfRjqix2XJZcpUSE_JeKF5am5a6LqLricv18gmUihZRrbmoBPIoI9Nivzjma8LuP-QNJFPbvIjIFpGH_ucUBoyE3aPVNSY-2qTxKkV0NbH9FS1pg0_stlpvJSY1IzSCSY5WbFUiSq3scrA41uWqUK4knS8q-PS6yrhks43EeL4IO5JtUA7rwORzg-pMtWLS4qhvlWgapDuDB4H3kD8RvMOKtZIGZYMW6bcL35ZMW1JrkN9KrTD27OajB1cEyKFVHCuhkAdpD9lZMBlYMkJtp2E8kZ0zu8ngSxBcRHuTwUZriUxd8L4ZMU_cJqLehdUY3dh4fjWcBDUQQgLDFNf1Rw45zJJQ7eA0mcFr-MRolwaVeJ6S_uJB42-_n6e23QQX8Q8jrsOsWlWS0Crwe39ARTFm4BfzMTvuh2lj0EmHcnh2p01LurkzumFb5uDOdsdOOaVg2OzHk-6e-ODb9EjoVopy_7klKzjGSnPM4BfN0ZMK5q5JCXZMcYleG3KIPccMPunW4hBFfj0NRFTg4eDVK_jGLdJSK2JC2WCbEjNbJGB28Of0wg4Pod-FRCA_S5CvpYPjwjaMyl1I5rmCV8J7uG0t6TpozErHXYdIZwsP4rxPdD4qQfNzpMlrP8mmW3BdtrXjyzj35j8LS6jQDK5mi2nSFuBGVeiJ0KjUGjWNjKMlox_ji3CPjgzW-oD_x9cld09_Ol8tPUoMNwik004nfKBKoOSQbaXeMBmnNS-9OPHyM6Ibbbgz0k0isaLEMC5am8Hq1ITr5eirUN2L4Yw_P4WGwTLQXnNxAG-bbVi53xrdKh5OZd55zR5KyazNi2jgsRkJbSQr97DRD0kQ-Ek_kvbAo-V98uY72LlHJfEB_mwtieoxKV0PGhCEtR1e_A3FxWFAGtfdcoilDxGKajKpXPxTb2xjtWwJ4a_k7aqIYIiPdJN3X0smy5ipcqdN_LIbh1EPpJs5vIZV-hbr-dd-sHH5_hcjtz132q3FbHrcQavpmci72B_iE-fc3x_9GObF1b_Dh2P-hX0nmNTbvAtGS393j4kRVX8ahpNyBrqJG875hLLREl0tWyKtigiIOX_4kBdR8qaIjkn0hQqVsWSQyh0YlIzEAYtoDO-ZuPxXA2i1x8fGoLV5F2MYYCCqGNM9PkKe5zB778o9m5_fr966n7RR96NBxdE86eVTE0-vlzEp_u3575k_-r8BrnaVIAsKAAA=

**Comment by Ennoriel** [comment]
For reference:
- [MVR](https://svelte-5-preview.vercel.app/?version=5.0.0-next.140#H4sIAAAAAAAACk2NTQrCMBBGrxJmbeg-FkG8gHvjoqQTCCaZYZJWpPTuJiLi8j2-nw18iFjA3DbIU0IwcGaGA9QXdygrxoqNCy3iuhmLk8D1ZLNSITFJVReKJNfgHijKCyVlvz09PbFQQu16QvMnYuFo8zj8Zhr8DwxNtb9Ec_ABZzBVFtzv-xtUg0KCqgAAAA==)
- [issue without the library](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACo2OuwrCQBBFf2WYJk1I-jUK_oOdsdDsBAeyD3YnQQn5d3eNKGJjeYdz554Zex4oojrOaM-GUOHeeyxR7j6HONEglHJ0Y-jypYldYC-71rbCxrsgcKAo0AdnoKjqHKq1ViQmUQMJaJ5a29Sfrm1WRnUuPbFkBeTKcTvn_gIXtlqlEtQJTvPGae6ZNCoJIy3l2zbj_-kC0O2p-_LZfAn9bpyWB8l2UJMdAQAA)

**Comment by Ennoriel** [comment]
This is fixed in the new Svelte 5 release ;)
