### ISSUE TITLE
Be able to position the Colourpicker above the label

### ISSUE THREAD

**Issue by adabingw** [Ennoriel/svelte-awesome-color-picker#77]
It'd be great if we could be able to position the Colourpicker above (or even to the left of/right of) the label. This lets us handle cases if, for example, our Colourpicker is too far down the screen, so that it can be shown above the label

Here's an image of what I'm talking about:

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/86745853/33eb3df8-dd79-4a0f-9541-f2482f5bb467)

As you can see, the Colourpicker is getting cutoff.

:)

**Comment by Ennoriel** [comment]
I don't know if I want to implement this in the library at the moment: beeing able to position it at the top right, at the top left, etc. especially because it's doable by [overriding the `Wrapper` component (REPL)](https://svelte.dev/repl/6fceb127a87f4c05ac8523c1b72a8252?version=4.2.18).
