### ISSUE TITLE
Bug: styling issue with picker handle on chromium based browsers

### ISSUE THREAD

**Issue by LeonHeidelbach** [Ennoriel/svelte-awesome-color-picker#81]
As the title says, there are some styling issues on chromium based browsers that show the horizontal and vertical slider rectangles used for the color picker handle. You can manually set the css style of the `.slider` class as well as the `::before` pseudo selector to `background-color: transparent` which fixes the issue. Strangely enough this issue does not appear on Firefox or Safari.

Browsers Tested (MacOS & Linux version):
Google Chrome 125.0.6422.142 (Official Build)

<img width="279" alt="image" src="https://github.com/user-attachments/assets/95552f3d-ead6-4693-8e26-5376a6477ab7">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/8ebe8183-cd6e-4ec9-9446-1cebc49c223d">

**Comment by Ennoriel** [comment]
I cannot reproduce this on Windows.

Could you write the exact css styling you've written to fix this? I'll update the slider library with it.

**Comment by LeonHeidelbach** [comment]
I will do this later today 👍🏻

**Comment by LeonHeidelbach** [comment]
@Ennoriel  I've had a look at the `svelte-awesome-slider` repo and simply making these style additions to the `.slider` class fixes the entire problem.

I added this here: [Slider.svelte](https://github.com/Ennoriel/svelte-awesome-slider/blob/0740b1a76c7f76865545d421ea7fb96409c0b3a9/src/lib/Slider.svelte#L191).
```patch
diff --git a/src/lib/Slider.svelte b/src/lib/Slider.svelte
index 887982d..028a55c 100644
--- a/src/lib/Slider.svelte
+++ b/src/lib/Slider.svelte
@@ -205,6 +205,11 @@
 		margin: auto;
 		user-select: none;
 		-webkit-user-select: none;
+		background-color: transparent;
+	}
+
+	.slider::before {
+		background-color: transparent;
 	}
 
 	[aria-orientation='horizontal'] {
```

**Comment by LeonHeidelbach** [comment]
@Ennoriel Did you see my proposed changes? It would really be great if this issue could be fixed soon :)
