### ISSUE TITLE
Feature: detect if dialog popup is within window bounds

### ISSUE THREAD

**Issue by LeonHeidelbach** [Ennoriel/svelte-awesome-color-picker#82]
My current issue with the dialog popup is that it does not dynamically adjust its fixed position to always be visible on screen. This causes the popup in some instances to be completely unusable when it is cut off by a weird window size. Some simple bounding rect checks and adjusting the dialog position to be above or below the color button depending on the available space would be nice. There should be an option on the component to enable/disable this feature like:

```svelte
<ColorPicker position="responsive" />
```

The available options could be: `fixed`, `responsive`, `responsive-x`, `responsive-y` with the latter two only adjusting the position on screen for the given axis.

**Comment by Ennoriel** [comment]
I release a new version with your PR. Thank you very much! 😃

**Comment by LeonHeidelbach** [comment]
@Ennoriel Great, thanks! It would also be nice, if the check that I implemented could be run right when the popup is created so that it immediately positions itself without any further DOM interaction. I played around with it a little but the issue was that when I tried to call the function whenever the variable `isOpen` changes, the initial width and height of the wrapper would be `0` so that my checks wouldn't work. I didn't have the time to dig any deeper, but maybe you could look into this because right now you need to either scroll the page or change the window size in order for the responsiveness to be triggered, and it would be great if it would do that once after triggering the popup :)

**Comment by Ennoriel** [comment]
`setTimeout` is not necessarily a bad thing. Utilizing `tick` can make it look better.

Before making any adjustments, I have a question. What was the reason for applying padding only on the y axis?

**Comment by LeonHeidelbach** [comment]
Using `setTimeout` for things like this can cause many issues that are difficult to debug later on as different machines might need more time to calculate the correct bounds of the div and the fixed timeout could be too short. Other than that setting a timeout in this situation does not really work as it would cause the popup to be initially drawn in the default location, and only after the timeout has elapsed, jump to the proper reactive location. This would introduce a "flicker" that is arguably worse than having to scroll the page before the popup is in the right spot.

> Before making any adjustments, I have a question. What was the reason for applying padding only on the y axis?

The padding was necessary so that the popup is properly aligned with the colour preview button. If you set the padding to `0`, you will see what I mean.
