### ISSUE TITLE
a way to specify position of the picker dialog relative to the button which opens it?

### ISSUE THREAD

**Issue by gizmolab10** [Ennoriel/svelte-awesome-color-picker#87]
the dialog opens with its top below the button and its left center-aligned on it. may I request an option to specify an offset relative to that point? i.e., the offset for that point is 0, 0. So, an offset of (-100, 0) would shift it left 100 pixels.

**Comment by Ennoriel** [comment]
The library is already super customizable. You can override most wrapper components and override the css.

Would that example suits you: https://svelte.dev/repl/6f7ee7d707bb4870ac717752f36fa3ca?version=4.2.19 ?

**Comment by gizmolab10** [comment]
PERFECT! Thank you. Did I miss this in your dox?

Sorry to ask again, is there a way to change the shape of the dot, to a rectangle of size w, h?

Jonathan Sand
Software Architect
***@***.***

**Comment by Ennoriel** [comment]
Which dot?

I updated the REPL.

**Comment by gizmolab10** [comment]
The button that appears next to the label, when the dialog is hidden.

Jonathan Sand
Software Architect
***@***.***

**Comment by Ennoriel** [comment]
It's not possible through props but you can override the css as I did with the picker indicator. ;)

**Comment by gizmolab10** [comment]
Great! Love it. What is the name of the css var whose border radius I can alter?

Jonathan Sand
Software Architect
***@***.***

**Comment by gizmolab10** [comment]
Maxine,

Thanks for your help a few months back. Following your guidance, I’m using these styles and props:

<style>
	div :global(.wrapper) {
		left: -83px;
		top: 24px;
	}

	div :global(.picker-indicator) {
		border-radius: 50%;
	}
</style>

<ColorPicker
	label=‘'
	hex={colorAsHEX}
	on:input={handleColorChange}
	--input-size='{selectorSize}px’
	--picker-width='{pickerSize}px’
	--picker-height='{pickerSize}px’
	--slider-width='{selectorSize}px’
	--picker-indicator-size='{selectorSize}px'/>

When clicked on the color dot, the picker appears 24px below it and 83px to its left. This is excellent.

I am writing you about something I did not notice until today: an issue with mouse click location. (1) A click in the color gradient bar moves the thumb to a position below the cursor. (2) A click in the gradient moves the color picker circle to a position to the left of the cursor. The misplacement distance is about 10px. Can you suggest something? Do you need more information?

Jonathan Sand
Software Architect
***@***.***

**Comment by gizmolab10** [comment]
Maxine,

Ack, I need to revise the question in my last email. My app uses a scaling transform which I’m pretty sure (I need to investigate it) explains the cursor displacement. Is there a way to compensate or does transform scaling uncorrectably distort the location computations inside the color picker?

Jonathan Sand
Software Architect
***@***.***
