### ISSUE TITLE
upgrade to svelte 5 

### ISSUE THREAD

**Issue by go-aegian** [Ennoriel/svelte-awesome-color-picker#89]
Are you planning to upgrade this component to Svelte 5?

Currently is unusable in a project that only supports svelte 5 without backward compatibility

**Comment by Ennoriel** [comment]
Can you be more specific? What do you mean by "**unusable** in a project that only supports svelte 5 without backward compatibility"?

I've made some changes in the past to make it compatible with Svelte 5. From my quick test today, I've found that overriding the components bring types error but it does not make it unusable.

Upgrading the component to Svelte 5 is in my plan though

**Comment by go-aegian** [comment]
I disagree with your statement about being usable as it's not when strictly using Svelte 5 with runes enabled. Unfortunately Svelte 5 changes a lot of community components and it will need a wave of upgrades throughout to finally have the community libs upgraded properly.

Below you can see the error being reported, hopefully it will help slowly port it to fully aligned with Svelte 5

```
[vite] error while updating dependencies:
Error: Build failed with 5 errors:
node_modules/svelte-awesome-color-picker/dist/components/ColorPicker.svelte:14:0: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-awesome-color-picker/dist/components/ColorPicker.svelte:14:0 Cannot use `export let` in runes mode — use `$props()` instead
node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11yHorizontalWrapper.svelte:2:0: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11yHorizontalWrapper.svelte:2:0 Cannot use `export let` in runes mode — use `$props()` instead
node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11yNotice.svelte:7:0: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11yNotice.svelte:7:0 Cannot use `export let` in runes mode — use `$props()` instead
node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11ySingleNotice.svelte:3:0: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-awesome-color-picker/dist/components/variant/accessibility/A11ySingleNotice.svelte:3:0 Cannot use `export let` in runes mode — use `$props()` instead
node_modules/svelte-awesome-color-picker/dist/components/variant/chrome-picker/Wrapper.svelte:2:0: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-awesome-color-picker/dist/components/variant/chrome-picker/Wrapper.svelte:2:0 Cannot use `export let` in runes mode — use `$props()` instead
```

**Comment by Ennoriel** [comment]
Today, I tested the following:

1. Create a new Svelte 5 repository with `npx sv create`
2. Install `svelte-awesome-color-picker` and used it in a `+page.svelte` file
3. Use runes in the `+page.svelte` file
4. Override `pickerIndicator` with a rune component

All of those tests were successful.

With you're last message, I don't know what you were trying to achieve. run `npm run dev`? `npm run build`?

Can you provide a reproduction example with the command you were executing? **This is the minimum information you should provide in any issue you open on Github.**

**Comment by go-aegian** [comment]
**- svelte.config.js** setup with
 
```
export default {
     compilerOptions: {
		runes:         true
     }
    ....
};
```

**- npm run dev**

**Comment by Ennoriel** [comment]
Thanks for that! I recognize that we were not talking of the same thing. This library is indeed compatible with a raw svelte 5 project or with any project working with the default config.

So, I checked what `compilerOptions: { runes: true }` does: 

> Will be true by default in Svelte 6. Note that setting this to true in your svelte.config.js will force runes mode for your entire project, including components in node_modules, which is likely not what you want. If you're using Vite, consider using [dynamicCompileOptions](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) instead.

May I ask why you want to work with this configuration while svelte 6 is not probably going to be released anytime soon?

**Comment by go-aegian** [comment]
Thanks for the info I removed that config setting and it compiled without it.

**Comment by go-aegian** [comment]
Thanks for the info I removed that config setting and it compiled without it.

**Comment by go-aegian** [comment]
Closing this issue, it might show up once Svelte 6 is out.
