### ISSUE TITLE
How to implement multiple pickers on same page bound to different colors?

### ISSUE THREAD

**Issue by twinmoonsllc** [Ennoriel/svelte-awesome-color-picker#9]
Currently, I am using the component as below:

<ColorPicker
            bind:rgb
            label="Edit"
            --picker-height="150px"
            --picker-width="150px"
          />

However, I would like to use one picker to set the background color for something and another picker to set the foreground. Being that it must be bound to the rgb variable, how can that be done? Maybe I'm not doing this correctly! Thanks.

**Comment by Ennoriel** [comment]
Hello @twinmoonsllc !

rgb is the inner variable name. You can bind it to a variable with another name:

```
<script>
  let background;
  let foreground;
</script>

<ColorPicker bind:rgb={background} />
<ColorPicker bind:rgb={foreground} />
```

**Comment by twinmoonsllc** [comment]
Silly me, I don't know what I was thinking. That works! Thank you.
